In [1]:
import sqlite3
import requests
script = requests.get('https://raw.githubusercontent.com/volkserg/DB2021/main/script.sql').text

# SQLite fixup
script = script.replace('COLLATE utf8mb4_unicode_ci','')
script = script.replace('ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci','')
script = script.replace("enum('M','F')",'blob(256)')
first_alter = script.index('ALTER')
script = script[:first_alter]
script = script.split('\n')
script = [i for i in script if not i.startswith('SET')]
script = '\n'.join(script)

import os
try:
    os.unlink('/tmp/db2021.sqlite')
except: pass
db = sqlite3.connect('/tmp/db2021.sqlite')
db.executescript(script)
db.commit()
db.close()

In [2]:
!pip install jupysql --user --break-system-packages

Requirement already satisfied: jupysql in /home/danya/.local/lib/python3.11/site-packages (0.10.2)
Requirement already satisfied: prettytable in /home/danya/.local/lib/python3.11/site-packages (from jupysql) (3.9.0)
Requirement already satisfied: ipython in /usr/lib/python3.11/site-packages (from jupysql) (8.16.0)
Requirement already satisfied: sqlalchemy in /home/danya/.local/lib/python3.11/site-packages (from jupysql) (2.0.21)
Requirement already satisfied: sqlparse in /home/danya/.local/lib/python3.11/site-packages (from jupysql) (0.4.4)
Requirement already satisfied: ipython-genutils>=0.1.0 in /home/danya/.local/lib/python3.11/site-packages (from jupysql) (0.2.0)
Requirement already satisfied: jinja2 in /usr/lib/python3.11/site-packages (from jupysql) (3.1.2)
Requirement already satisfied: sqlglot>=11.3.7 in /home/danya/.local/lib/python3.11/site-packages (from jupysql) (18.12.0)
Requirement already satisfied: ploomber-core>=0.2.7 in /home/danya/.local/lib/python3.11/site-packages (from jupysql) (0.2.14)
Requirement already satisfied: jupysql-plugin in /home/danya/.local/lib/python3.11/site-packages (from jupysql) (0.2.5)
Requirement already satisfied: click in /usr/lib/python3.11/site-packages (from ploomber-core>=0.2.7->jupysql) (8.1.7)
Requirement already satisfied: pyyaml in /usr/lib/python3.11/site-packages (from ploomber-core>=0.2.7->jupysql) (6.0.1)
Requirement already satisfied: posthog in /home/danya/.local/lib/python3.11/site-packages (from ploomber-core>=0.2.7->jupysql) (3.0.2)
Requirement already satisfied: backcall in /usr/lib/python3.11/site-packages (from ipython->jupysql) (0.2.0)
Requirement already satisfied: decorator in /usr/lib/python3.11/site-packages (from ipython->jupysql) (5.1.1)
Requirement already satisfied: jedi>=0.16 in /usr/lib/python3.11/site-packages (from ipython->jupysql) (0.19.0)
Requirement already satisfied: matplotlib-inline in /usr/lib/python3.11/site-packages (from ipython->jupysql) (0.1.6)
Requirement already satisfied: pickleshare in /usr/lib/python3.11/site-packages (from ipython->jupysql) (0.7.5)
Requirement already satisfied: prompt-toolkit!=3.0.37,<3.1.0,>=3.0.30 in /usr/lib/python3.11/site-packages (from ipython->jupysql) (3.0.39)
Requirement already satisfied: pygments>=2.4.0 in /usr/lib/python3.11/site-packages (from ipython->jupysql) (2.16.1)
Requirement already satisfied: stack-data in /usr/lib/python3.11/site-packages (from ipython->jupysql) (0.6.3)
Requirement already satisfied: traitlets>=5 in /usr/lib/python3.11/site-packages (from ipython->jupysql) (5.11.2)
Requirement already satisfied: pexpect>4.3 in /usr/lib/python3.11/site-packages (from ipython->jupysql) (4.8.0)
Requirement already satisfied: MarkupSafe>=2.0 in /usr/lib/python3.11/site-packages (from jinja2->jupysql) (2.1.3)
Requirement already satisfied: wcwidth in /usr/lib/python3.11/site-packages (from prettytable->jupysql) (0.2.8)
Requirement already satisfied: typing-extensions>=4.2.0 in /usr/lib/python3.11/site-packages (from sqlalchemy->jupysql) (4.8.0)
Requirement already satisfied: greenlet!=0.4.17 in /home/danya/.local/lib/python3.11/site-packages (from sqlalchemy->jupysql) (2.0.2)
Requirement already satisfied: parso<0.9.0,>=0.8.3 in /usr/lib/python3.11/site-packages (from jedi>=0.16->ipython->jupysql) (0.8.3)
Requirement already satisfied: requests<3.0,>=2.7 in /home/danya/.local/lib/python3.11/site-packages (from posthog->ploomber-core>=0.2.7->jupysql) (2.31.0)
Requirement already satisfied: six>=1.5 in /usr/lib/python3.11/site-packages (from posthog->ploomber-core>=0.2.7->jupysql) (1.16.0)
Requirement already satisfied: monotonic>=1.5 in /home/danya/.local/lib/python3.11/site-packages (from posthog->ploomber-core>=0.2.7->jupysql) (1.6)
Requirement already satisfied: backoff>=1.10.0 in /home/danya/.local/lib/python3.11/site-packages (from posthog->ploomber-core>=0.2.7->jupysql) (2.2.1)
Requirement already satisfied: python-dateutil>2.1 in /usr/lib/python3.11/site-packages (from posthog->ploomber-core>=0.2.7->jupysql) (2.8.2)
Requirement already satisfied: executing>=1.2.0 in /usr/lib/python3.11/site-packages (from stack-data->ipython->jupysql) (2.0.0)
Requirement already satisfied: asttokens>=2.1.0 in /usr/lib/python3.11/site-packages (from stack-data->ipython->jupysql) (2.4.0)
Requirement already satisfied: pure-eval in /usr/lib/python3.11/site-packages (from stack-data->ipython->jupysql) (0.2.2)
Requirement already satisfied: charset-normalizer<4,>=2 in /home/danya/.local/lib/python3.11/site-packages (from requests<3.0,>=2.7->posthog->ploomber-core>=0.2.7->jupysql) (3.2.0)
Requirement already satisfied: idna<4,>=2.5 in /usr/lib/python3.11/site-packages (from requests<3.0,>=2.7->posthog->ploomber-core>=0.2.7->jupysql) (3.4)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/lib/python3.11/site-packages (from requests<3.0,>=2.7->posthog->ploomber-core>=0.2.7->jupysql) (1.26.15)
Requirement already satisfied: certifi>=2017.4.17 in /usr/lib/python3.11/site-packages (from requests<3.0,>=2.7->posthog->ploomber-core>=0.2.7->jupysql) (2023.7.22)

In [3]:
%load_ext sql

In [4]:
%sql sqlite:////tmp/db2021.sqlite

Connecting to 'sqlite:////tmp/db2021.sqlite'

In [5]:
%%sql
SELECT * FROM sqlite_master

Running query in 'sqlite:////tmp/db2021.sqlite'

+-------+------+----------+----------+-------------------------------------+
|  type | name | tbl_name | rootpage |                 sql                 |
+-------+------+----------+----------+-------------------------------------+
| table | ИЖД  |   ИЖД    |    2     |         CREATE TABLE `ИЖД` (        |
|       |      |          |          |        `Код` int(11) NOT NULL,      |
|       |      |          |          |      `Имя` varchar(15)  NOT NULL,   |
|       |      |          |          |       `Пол` blob(256)  NOT NULL,    |
|       |      |          |          |         `Дрожд` date NOT NULL,      |
|       |      |          |          |     `СтРод` varchar(10)  NOT NULL   |
|       |      |          |          |                  )                  |
| table | О_М  |   О_М    |    50    |         CREATE TABLE `О_М` (        |
|       |      |          |          |         `No` int(11) NOT NULL,      |
|       |      |          |          |     `Место` varchar(20)  NOT NULL   |
|       |      |          |          |                  )                  |
| table |  ОТ  |    ОТ    |    54    |         CREATE TABLE `ОТ` (         |
|       |      |          |          |         `No` int(11) NOT NULL,      |
|       |      |          |          |         `Назв` text  NOT NULL,      |
|       |      |          |          |        `КодР` int(11) NOT NULL,     |
|       |      |          |          |          `НачР` date NOT NULL       |
|       |      |          |          |                  )                  |
| table |  ПР  |    ПР    |    59    |         CREATE TABLE `ПР` (         |
|       |      |          |          |         `Np` int(11) NOT NULL,      |
|       |      |          |          |     `Назв` varchar(20)  NOT NULL,   |
|       |      |          |          |     `Место` varchar(20)  NOT NULL,  |
|       |      |          |          |         `Noo` int(11) NOT NULL      |
|       |      |          |          |                  )                  |
| table | Р_Н  |   Р_Н    |    70    |         CREATE TABLE `Р_Н` (        |
|       |      |          |          |        `Код` int(11) NOT NULL,      |
|       |      |          |          |         `Np` int(11) NOT NULL,      |
|       |      |          |          |        `Время` int(11) NOT NULL     |
|       |      |          |          |                  )                  |
| table |  СЛ  |    СЛ    |   102    |         CREATE TABLE `СЛ` (         |
|       |      |          |          |        `Код` int(11) NOT NULL,      |
|       |      |          |          |    `Фамилия` varchar(15)  NOT NULL, |
|       |      |          |          |      `Имя` varchar(15)  NOT NULL,   |
|       |      |          |          |   `Отчество` varchar(15)  NOT NULL, |
|       |      |          |          |       `Пол` blob(256)  NOT NULL,    |
|       |      |          |          |        `Адрес` text  NOT NULL,      |
|       |      |          |          |      `Зарплата` int(11) NOT NULL,   |
|       |      |          |          |         `Дрожд` date NOT NULL,      |
|       |      |          |          |         `No` int(11) NOT NULL,      |
|       |      |          |          |      `КодК` int(11) DEFAULT NULL    |
|       |      |          |          |                  )                  |
+-------+------+----------+----------+-------------------------------------+

# Замечание по поводу CTE
Этот документ создан с помощью Jupyter Lab с помощью расширения JupySQL.
Это расширение позволяет использовать специальный синтаксис, чтобы использовать запросы в качестве *Common Table Expressions* (CTE).

Следующее выражение в классическом SQL:

In [6]:
%%sql
WITH all_employee_codes AS (SELECT Код FROM СЛ),
    employees_with_deps_codes AS (SELECT СЛ.Код FROM СЛ JOIN ИЖД ON СЛ.Код = ИЖД.Код)
SELECT * FROM (
    SELECT * FROM all_employee_codes
    EXCEPT
    SELECT * FROM employees_with_deps_codes
)

Running query in 'sqlite:////tmp/db2021.sqlite'

+-----+
| Код |
+-----+
|  2  |
|  3  |
|  5  |
|  6  |
|  8  |
|  9  |
|  10 |
|  11 |
|  12 |
|  14 |
+-----+
Truncated to displaylimit of 10.

... можно записать следующим образом, выделив CTE-выражения в свои собственные ячейки:

In [7]:
%%sql --save all_employee_codes --no-execute
SELECT Код FROM СЛ

Running query in 'sqlite:////tmp/db2021.sqlite'

Skipping execution...

In [8]:
%%sql --save employees_with_deps_codes --no-execute
SELECT СЛ.Код FROM СЛ JOIN ИЖД ON СЛ.Код = ИЖД.Код

Running query in 'sqlite:////tmp/db2021.sqlite'

Skipping execution...

In [9]:
%%sql --with all_employee_codes --with employees_with_deps_codes
SELECT * FROM all_employee_codes
EXCEPT
SELECT * FROM employees_with_deps_codes

Running query in 'sqlite:////tmp/db2021.sqlite'

+-----+
| Код |
+-----+
|  2  |
|  3  |
|  5  |
|  6  |
|  8  |
|  9  |
|  10 |
|  11 |
|  12 |
|  14 |
+-----+
Truncated to displaylimit of 10.

Запустите эти ячейки без команды `--no-execute`, чтобы увидеть содержимое промежуточных таблиц.

Измените значение в ячейке ниже, чтобы изменить количество строк, которые выводятся в ячейках ответа.

In [10]:
%config SqlMagic.displaylimit = 15

В приведенной базе данных данные недостаточны, чтобы получить ответ на все задания.
Например, для задания 1.7, не существует отдела с названием "Информатика",
поэтому, если написать запрос в точности по заданию,
то количество строк вывода будет равно нулю.

В случаях, когда можно получить ненулевой результат, изменив константы в запросе,
я сделал это, оставив пометку `!!ДАННЫЕ ИЗМЕНЕНЫ!!`.

Эта база данных также обладает свойством: каждый сотрудник работает только над проектами, за которые ответственный его отдел.
Из-за этого некоторые запросов (среди них 1.13, 2.3, 3.6, 3.8, 3.9) имеют тривиальные наборы результатов (либо пустые, либо содержащие весь набор проектов).

---

# 1.6. Имена служащих, имеющих, по крайней мере, одного иждивенца.

In [11]:
%%sql
SELECT СЛ.Имя, "|||", *
FROM СЛ JOIN ИЖД ON ИЖД.Код = СЛ.Код -- после JOIN остаются только строки для сотрудников которые имеют иждивенцев 
GROUP BY СЛ.Код -- выделить только одну строку на сотрудника

Running query in 'sqlite:////tmp/db2021.sqlite'

+-----------+-------+-----+------------+-----------+---------------+-----+------------------------------------------------+----------+------------+-----+------+-------+-----------+-------+------------+--------+
|    Имя    | "|||" | Код |  Фамилия   |   Имя_1   |    Отчество   | Пол |                     Адрес                      | Зарплата |   Дрожд    |  No | КодК | Код_1 |   Имя_2   | Пол_1 |  Дрожд_1   | СтРод  |
+-----------+-------+-----+------------+-----------+---------------+-----+------------------------------------------------+----------+------------+-----+------+-------+-----------+-------+------------+--------+
|    Лора   |  |||  |  1  |  Ефремова  |    Лора   |   Эльдаровна  |  F  | ст. Самара, ул. 40 лет Октября, д. 13, 785499  |  49142   | 1990-09-22 | 118 | None |   1   |   Раиса   |   F   | 1983-07-16 | Сестра |
|   Ксения  |  |||  |  4  |  Кузьмина  |   Ксения  |   Богдановна  |  F  |   к. Белгород, ул. Урожайная, д. 11, 114899    |  104714  | 1968-09-04 | 121 | 5778 |   4   |   Ермил   |   M   | 1993-09-10 |  Сын   |
|   Трофим  |  |||  |  7  |   Чернов   |   Трофим  |   Гордеевич   |  M  |    п. Буденновск, ул. Труда, д. 48, 525036     |  60405   | 1965-08-14 |  97 | None |   7   |   Анжела  |   F   | 1934-03-14 |  Мать  |
|  Феврония |  |||  |  13 |  Кабанова  |  Феврония |  Аскольдовна  |  F  |   ст. Ярославль, ул. Дарвина, д. 47, 366771    |  42498   | 1995-01-26 | 113 | 3057 |   13  |  Вероника |   F   | 1961-07-16 |  Мать  |
|   Иосиф   |  |||  |  15 |  Суханов   |   Иосиф   |   Валерьевич  |  M  |  п. Домбай, ул. Геологическая, д. 41, 417323   |  70146   | 1980-08-17 |  96 | 4867 |   15  |   Галина  |   F   | 1950-10-02 |  Мать  |
|   Анжела  |  |||  |  16 | Горбунова  |   Анжела  |   Андреевна   |  F  |    с. Арсеньев, ул. Казачья, д. 00, 023243     |  70297   | 1954-02-07 |  3  | None |   16  | Елизавета |   F   | 1955-04-20 | Сестра |
|  Герасим  |  |||  |  27 |  Суворов   |  Герасим  |   Демьянович  |  M  |    с. Нерчинск, ул. Невского, д. 36, 784119    |  57654   | 1969-12-20 |  41 | None |   27  |  Вероника |   F   | 1936-01-04 |  Мать  |
|  Никифор  |  |||  |  28 |  Анисимов  |  Никифор  |   Анисимович  |  M  | п. Неплюевка, ул. Механизаторов, д. 52, 277511 |  65578   | 1970-10-17 |  96 | None |   28  |   Агафон  |   M   | 2004-07-31 |  Сын   |
| Маргарита |  |||  |  31 |  Хохлова   | Маргарита |   Леонидовна  |  F  |  п. Ноглики, ул. Красноярская, д. 07, 885764   |  66155   | 1969-06-27 | 131 | None |   31  |  Евгений  |   M   | 1979-03-16 |  Брат  |
|    Тит    |  |||  |  35 | Кондратьев |    Тит    |    Фадеевич   |  M  |    ст. Соловки, ул. Короткая, д. 75, 792340    |  48579   | 1979-08-25 |  76 | None |   35  |    Вера   |   F   | 1998-10-20 |  Дочь  |
|   Денис   |  |||  |  37 |  Андреев   |   Денис   |   Ааронович   |  M  |    г. Усть-Кулом, ул. Чехова, д. 23, 582131    |  57222   | 1965-07-21 |  70 | None |   37  |  Леонтий  |   M   | 1985-05-15 |  Сын   |
|  Силантий |  |||  |  40 |   Маслов   |  Силантий |   Ефимьевич   |  M  | с. Горячинск, ул. Физкультурная, д. 16, 476112 |  90161   | 1956-12-30 | 109 | None |   40  |   Ефрем   |   M   | 1947-07-12 |  Брат  |
|    Егор   |  |||  |  41 |   Крылов   |    Егор   | Брониславович |  M  |   с. Томпа, ул. Ленинградская, д. 44, 475801   |  47181   | 1998-06-16 |  79 | None |   41  |   Ульян   |   M   | 1972-11-02 |  Отец  |
|    Иван   |  |||  |  45 |  Поляков   |    Иван   |   Артемьевич  |  M  | ст. Соболево, ул. Орджоникидзе, д. 92, 370434  |  75469   | 1977-11-09 |  57 | None |   45  |   Раиса   |   F   | 1999-09-26 |  Дочь  |
|  Любомир  |  |||  |  51 |  Шестаков  |  Любомир  |   Ильясович   |  M  | с. Прохладный, ул. Ярославская, д. 49, 663935  |  86363   | 1983-11-17 |  39 | None |   51  |   Евсей   |   M   | 2006-07-10 |  Сын   |
+-----------+-------+-----+------------+-----------+---------------+-----+------------------------------------------------+----------+------------+-----+------+-------+-----------+-------+------------+--------+
Truncated to displaylimit of 15.

# 1.7. Имена служащих, работающих в отделе с названием «Информатика» над проектом с названием «Прогресс»

In [12]:
%%sql
SELECT СЛ.Имя, "|||", *
FROM СЛ -- для каждого сотрудника
    JOIN ОТ ON ОТ.No = СЛ.No -- находим его отдел
    JOIN Р_Н ON СЛ.Код = Р_Н.Код -- над какими проектами сотрудник работает
    JOIN ПР ON ПР.Np = Р_Н.Np -- и как эти проекты называются
WHERE
    ОТ.Назв = "Отдел информатизации внутренних операций" -- !!ДАННЫЕ ИЗМЕНЕНЫ!!
    AND ПР.Назв = "GEBKN-54860-JIWYR" -- !!ДАННЫЕ ИЗМЕНЕНЫ!!

Running query in 'sqlite:////tmp/db2021.sqlite'

+-----------+-------+------+------------+-----------+----------------+-----+---------------------------------------------------------+----------+------------+-----+------+------+------------------------------------------+------+------------+-------+-----+-------+------+-------------------+----------+-----+
|    Имя    | "|||" | Код  |  Фамилия   |   Имя_1   |    Отчество    | Пол |                          Адрес                          | Зарплата |   Дрожд    |  No | КодК | No_1 |                   Назв                   | КодР |    НачР    | Код_1 |  Np | Время | Np_1 |       Назв_1      |  Место   | Noo |
+-----------+-------+------+------------+-----------+----------------+-----+---------------------------------------------------------+----------+------------+-----+------+------+------------------------------------------+------+------------+-------+-----+-------+------+-------------------+----------+-----+
| Харлампий |  |||  | 339  |  Савельев  | Харлампий |   Игнатьевич   |  M  |        п. Чебоксары, ул. Крупской, д. 19, 911463        |  68021   | 1954-04-01 | 121 | None | 121  | Отдел информатизации внутренних операций | 1272 | 2018-04-04 |  339  | 643 |   5   | 643  | GEBKN-54860-JIWYR | п. Хасан | 121 |
|  Светозар |  |||  | 349  |  Рыбаков   |  Светозар |   Игнатович    |  M  |       с. Баргузин, ул. Декабристов, д. 92, 078707       |  42220   | 1996-02-15 | 121 | None | 121  | Отдел информатизации внутренних операций | 1272 | 2018-04-04 |  349  | 643 |   7   | 643  | GEBKN-54860-JIWYR | п. Хасан | 121 |
|   Лариса  |  |||  | 606  |  Маркова   |   Лариса  |   Семеновна    |  F  |     г. Владивосток, ул. 40 лет Победы, д. 44, 126411    |  60173   | 1999-12-19 | 121 | None | 121  | Отдел информатизации внутренних операций | 1272 | 2018-04-04 |  606  | 643 |   7   | 643  | GEBKN-54860-JIWYR | п. Хасан | 121 |
|    Лев    |  |||  | 608  |  Соболев   |    Лев    |   Антипович    |  M  |          клх Чулым, ул. Рылеева, д. 67, 770816          |  65947   | 1961-01-05 | 121 | None | 121  | Отдел информатизации внутренних операций | 1272 | 2018-04-04 |  608  | 643 |   7   | 643  | GEBKN-54860-JIWYR | п. Хасан | 121 |
|  Светлана |  |||  | 1600 | Воробьева  |  Светлана |   Руслановна   |  F  |         клх Губаха, ул. Заводская, д. 43, 399818        |  96513   | 1957-09-24 | 121 | None | 121  | Отдел информатизации внутренних операций | 1272 | 2018-04-04 |  1600 | 643 |   7   | 643  | GEBKN-54860-JIWYR | п. Хасан | 121 |
|  Элеонора |  |||  | 1634 |   Рогова   |  Элеонора |   Аркадьевна   |  F  |    д. Петрозаводск, ул. Высоковольтная, д. 96, 996077   |  60539   | 1970-08-28 | 121 | None | 121  | Отдел информатизации внутренних операций | 1272 | 2018-04-04 |  1634 | 643 |   11  | 643  | GEBKN-54860-JIWYR | п. Хасан | 121 |
|  Афиноген |  |||  | 1785 | Владимиров |  Афиноген |   Денисович    |  M  |            клх Аша, ул. 9 Мая, д. 66, 168372            |  104440  | 1989-01-22 | 121 | 761  | 121  | Отдел информатизации внутренних операций | 1272 | 2018-04-04 |  1785 | 643 |   12  | 643  | GEBKN-54860-JIWYR | п. Хасан | 121 |
| Ростислав |  |||  | 2405 |  Журавлев  | Ростислав |   Ильясович    |  M  |          д. Палана, ул. Тульская, д. 61, 871884         |  63432   | 1983-06-27 | 121 | 5778 | 121  | Отдел информатизации внутренних операций | 1272 | 2018-04-04 |  2405 | 643 |   14  | 643  | GEBKN-54860-JIWYR | п. Хасан | 121 |
|  Глафира  |  |||  | 2735 | Кузнецова  |  Глафира  |   Максимовна   |  F  |          с. Шелехов, ул. Дружбы, д. 45, 891318          |  72268   | 1982-02-18 | 121 | None | 121  | Отдел информатизации внутренних операций | 1272 | 2018-04-04 |  2735 | 643 |   7   | 643  | GEBKN-54860-JIWYR | п. Хасан | 121 |
|    Вера   |  |||  | 2847 | Агафонова  |    Вера   |    Ивановна    |  F  |  ст. Солнечногорск, ул. Коммунистическая, д. 00, 490168 |  71419   | 1956-11-03 | 121 | None | 121  | Отдел информатизации внутренних операций | 1272 | 2018-04-04 |  2847 | 643 |   9   | 643  | GEBKN-54860-JIWYR | п. Хасан | 121 |
|   Иванна  |  |||  | 3191 | Щербакова  |   Иванна  |   Дмитриевна   |  F  |       клх Нефтекамск, ул. Ореховая, д. 27, 324012       |  81964   | 1981-03-02 | 121 | None | 121  | Отдел информатизации внутренних операций | 1272 | 2018-04-04 |  3191 | 643 |   9   | 643  | GEBKN-54860-JIWYR | п. Хасан | 121 |
| Евпраксия |  |||  | 3272 |  Филатова  | Евпраксия | Константиновна |  F  | ст. Октябрьское (Челяб.), ул. Украинская, д. 30, 492324 |  60981   | 1974-06-27 | 121 | None | 121  | Отдел информатизации внутренних операций | 1272 | 2018-04-04 |  3272 | 643 |   11  | 643  | GEBKN-54860-JIWYR | п. Хасан | 121 |
|   Феликс  |  |||  | 3706 |  Романов   |   Феликс  |   Денисович    |  M  |          д. Мелеуз, ул. Союзная, д. 95, 308405          |  45653   | 1987-03-26 | 121 | 4300 | 121  | Отдел информатизации внутренних операций | 1272 | 2018-04-04 |  3706 | 643 |   7   | 643  | GEBKN-54860-JIWYR | п. Хасан | 121 |
|    Алла   |  |||  | 4072 | Пономарева |    Алла   |   Сергеевна    |  F  |           к. Шуя, ул. Урицкого, д. 20, 490588           |  69178   | 1970-09-21 | 121 | None | 121  | Отдел информатизации внутренних операций | 1272 | 2018-04-04 |  4072 | 643 |   13  | 643  | GEBKN-54860-JIWYR | п. Хасан | 121 |
|    Анна   |  |||  | 4153 | Родионова  |    Анна   |  Анатольевна   |  F  |          д. Кежма, ул. Полярная, д. 51, 800273          |  66114   | 1968-05-16 | 121 | None | 121  | Отдел информатизации внутренних операций | 1272 | 2018-04-04 |  4153 | 643 |   9   | 643  | GEBKN-54860-JIWYR | п. Хасан | 121 |
+-----------+-------+------+------------+-----------+----------------+-----+---------------------------------------------------------+----------+------------+-----+------+------+------------------------------------------+------+------------+-------+-----+-------+------+-------------------+----------+-----+
Truncated to displaylimit of 15.

# 1.8. Имена служащих и имена его иждивенцев.

In [13]:
%%sql
SELECT СЛ.Имя, GROUP_CONCAT(ИЖД.Имя) FROM СЛ JOIN ИЖД ON ИЖД.Код = СЛ.Код GROUP BY СЛ.Код ORDER BY COUNT(ИЖД.Имя) DESC

Running query in 'sqlite:////tmp/db2021.sqlite'

+------------+------------------------------------------------------------+
|    Имя     |                   GROUP_CONCAT(ИЖД.Имя)                    |
+------------+------------------------------------------------------------+
|   Ермил    | Анжела,Дарья,Епифан,Лариса,Леонтий,Любовь,Ольга,Твердислав |
|    Майя    |   Агафон,Василиса,Галина,Корнил,Ольга,Севастьян,Тимофей    |
|   Фаина    |  Антонина,Вячеслав,Глафира,Раиса,Севастьян,Стоян,Терентий  |
|   Тамара   |         Агафон,Вероника,Глафира,Казимир,Любовь,Ян          |
|   Фёкла    |      Антонина,Викторин,Ираида,Натан,Синклитикия,Фадей      |
|   Прохор   |          Гурий,Нинель,Регина,Сократ,Творимир,Фрол          |
|  Онуфрий   |     Агап,Василиса,Вероника,Евфросиния,Октябрина,Раиса      |
|     Ия     |           Аггей,Ираида,Казимир,Лора,Нина,Ульяна            |
|  Элеонора  |         Василиса,Галина,Евгений,Спартак,Тимофей,Ян         |
| Лаврентий  |         Василиса,Ермил,Казимир,Стоян,Твердислав,Ян         |
|   Макар    |    Аггей,Варфоломей,Вячеслав,Зиновий,Сократ,Твердислав     |
|  Соломон   |         Агафон,Антонина,Любовь,Нинель,Октябрина,Ян         |
| Прасковья  |      Агафон,Варлаам,Вероника,Гурий,Севастьян,Тимофей       |
| Евфросиния |   Варфоломей,Вячеслав,Глафира,Елизавета,Корнил,Радислав    |
|    Анна    |              Анжела,Всемил,Нина,Нинель,Фадей               |
+------------+------------------------------------------------------------+
Truncated to displaylimit of 15.

# 1.9. Названия проектов, за которые отвечает отдел, руководимый Ивановым

In [14]:
%%sql
SELECT ПР.Назв, "|||", *
FROM ПР
    JOIN ОТ ON ПР.Noo = ОТ.No -- для проекта, отвечающий отдел
    JOIN СЛ ON СЛ.Код = ОТ.КодР -- для отдела, его начальник
WHERE
    СЛ.Фамилия = "Игнатов" -- !!ДАННЫЕ ИЗМЕНЕНЫ!!

Running query in 'sqlite:////tmp/db2021.sqlite'

+-------------------+-------+-----+-------------------+------------------+-----+----+-------------------------------------------+------+------------+------+---------+---------+------------+-----+-------------------------------------------+----------+------------+------+------+
|        Назв       | "|||" |  Np |       Назв_1      |      Место       | Noo | No |                   Назв_2                  | КодР |    НачР    | Код  | Фамилия |   Имя   |  Отчество  | Пол |                   Адрес                   | Зарплата |   Дрожд    | No_1 | КодК |
+-------------------+-------+-----+-------------------+------------------+-----+----+-------------------------------------------+------+------------+------+---------+---------+------------+-----+-------------------------------------------+----------+------------+------+------+
| LZHRN-29314-SWGJG |  |||  |  36 | LZHRN-29314-SWGJG | д. Южно-Курильск |  60 | 60 | Отдел содержания промежуточных разработок | 3450 | 2013-07-31 | 3450 | Игнатов | Лучезар | Демьянович |  M  | д. Сортавала, ул. Осипенко, д. 87, 770573 |  231246  | 1963-07-30 |  60  | None |
| MXJRY-69039-RFVHJ |  |||  | 334 | MXJRY-69039-RFVHJ |    клх Кыштым    |  60 | 60 | Отдел содержания промежуточных разработок | 3450 | 2013-07-31 | 3450 | Игнатов | Лучезар | Демьянович |  M  | д. Сортавала, ул. Осипенко, д. 87, 770573 |  231246  | 1963-07-30 |  60  | None |
| THZIR-56023-CJNHM |  |||  | 453 | THZIR-56023-CJNHM |  с. Курганинск   |  60 | 60 | Отдел содержания промежуточных разработок | 3450 | 2013-07-31 | 3450 | Игнатов | Лучезар | Демьянович |  M  | д. Сортавала, ул. Осипенко, д. 87, 770573 |  231246  | 1963-07-30 |  60  | None |
| VYQZL-35713-BDIQM |  |||  | 467 | VYQZL-35713-BDIQM |    г. Домбай     |  60 | 60 | Отдел содержания промежуточных разработок | 3450 | 2013-07-31 | 3450 | Игнатов | Лучезар | Демьянович |  M  | д. Сортавала, ул. Осипенко, д. 87, 770573 |  231246  | 1963-07-30 |  60  | None |
| WQIJO-85931-DMMDW |  |||  | 562 | WQIJO-85931-DMMDW |    клх Кыштым    |  60 | 60 | Отдел содержания промежуточных разработок | 3450 | 2013-07-31 | 3450 | Игнатов | Лучезар | Демьянович |  M  | д. Сортавала, ул. Осипенко, д. 87, 770573 |  231246  | 1963-07-30 |  60  | None |
| MEVRO-95202-RZJCW |  |||  | 677 | MEVRO-95202-RZJCW |    ст. Кяхта     |  60 | 60 | Отдел содержания промежуточных разработок | 3450 | 2013-07-31 | 3450 | Игнатов | Лучезар | Демьянович |  M  | д. Сортавала, ул. Осипенко, д. 87, 770573 |  231246  | 1963-07-30 |  60  | None |
| KDUUZ-56128-QMSUK |  |||  | 769 | KDUUZ-56128-QMSUK |    клх Крымск    |  60 | 60 | Отдел содержания промежуточных разработок | 3450 | 2013-07-31 | 3450 | Игнатов | Лучезар | Демьянович |  M  | д. Сортавала, ул. Осипенко, д. 87, 770573 |  231246  | 1963-07-30 |  60  | None |
+-------------------+-------+-----+-------------------+------------------+-----+----+-------------------------------------------+------+------------+------+---------+---------+------------+-----+-------------------------------------------+----------+------------+------+------+

# 1.10 Названия отделов, отвечающих за проекты с названием «Принцип …»

In [15]:
%%sql
SELECT ОТ.Назв, "|||", *
FROM ОТ
    JOIN ПР ON ПР.Noo = ОТ.No -- отделы и их проекты
WHERE
    ПР.Назв LIKE "%-29314-%" -- !!ДАННЫЕ ИЗМЕНЕНЫ!!

Running query in 'sqlite:////tmp/db2021.sqlite'

+-------------------------------------------+-------+----+-------------------------------------------+------+------------+----+-------------------+------------------+-----+
|                    Назв                   | "|||" | No |                   Назв_1                  | КодР |    НачР    | Np |       Назв_2      |      Место       | Noo |
+-------------------------------------------+-------+----+-------------------------------------------+------+------------+----+-------------------+------------------+-----+
| Отдел содержания промежуточных разработок |  |||  | 60 | Отдел содержания промежуточных разработок | 3450 | 2013-07-31 | 36 | LZHRN-29314-SWGJG | д. Южно-Курильск |  60 |
+-------------------------------------------+-------+----+-------------------------------------------+------+------------+----+-------------------+------------------+-----+

# 1.11 Имена курируемых, работающих в том же отделе что и куратор.

In [16]:
%%sql
WITH trainer AS (SELECT * FROM СЛ), -- берем две копии таблицы сотрудников
    trainee AS (SELECT * FROM СЛ) -- с двумя разными названиями
SELECT trainee.Имя, "|||", *
FROM trainee
    JOIN trainer ON trainer.Код = trainee.КодК -- один является куратором другого
WHERE trainer.No = trainee.No -- и их отдел совпадает

Running query in 'sqlite:////tmp/db2021.sqlite'

+-------------+-------+-----+------------+-------------+---------------+-----+---------------------------------------------------------+----------+------------+-----+------+-------+-----------+------------+---------------+-------+------------------------------------------------------+------------+------------+------+--------+
|     Имя     | "|||" | Код |  Фамилия   |    Имя_1    |    Отчество   | Пол |                          Адрес                          | Зарплата |   Дрожд    |  No | КодК | Код_1 | Фамилия_1 |   Имя_2    |   Отчество_1  | Пол_1 |                       Адрес_1                        | Зарплата_1 |  Дрожд_1   | No_1 | КодК_1 |
+-------------+-------+-----+------------+-------------+---------------+-----+---------------------------------------------------------+----------+------------+-----+------+-------+-----------+------------+---------------+-------+------------------------------------------------------+------------+------------+------+--------+
|    Прохор   |  |||  |  2  |   Туров    |    Прохор   |   Ильясович   |  M  |       д. Сосногорск, ул. Кубанская, д. 15, 004581       |  57947   | 1994-02-12 |  98 | 5359 |  5359 |  Потапова |   Ксения   |   Натановна   |   F   |        с. Подольск, ул. Минина, д. 79, 306165        |   82991    | 1958-12-12 |  98  |  None  |
|    Ксения   |  |||  |  4  |  Кузьмина  |    Ксения   |   Богдановна  |  F  |        к. Белгород, ул. Урожайная, д. 11, 114899        |  104714  | 1968-09-04 | 121 | 5778 |  5778 |  Фомичев  |   Мариан   |   Филатович   |   M   |        с. Карталы, ул. Громова, д. 23, 403236        |   90598    | 1967-09-28 | 121  |  None  |
|   Анжелика  |  |||  |  8  |  Крылова   |   Анжелика  |    Петровна   |  F  |         клх Москва, ул. Колхозная, д. 30, 992177        |  39391   | 1996-07-04 |  99 | 4584 |  4584 |   Уваров  |    Глеб    |  Венедиктович |   M   |     с. Москва, ул. Высоковольтная, д. 14, 583265     |   96276    | 1965-02-02 |  99  |  None  |
|   Татьяна   |  |||  |  9  |  Сазонова  |   Татьяна   |   Алексеевна  |  F  |          к. Находка, ул. Моховая, д. 95, 386652         |  79839   | 1972-08-19 |  44 | 3262 |  3262 |  Степанов |   Ермил    |  Герасимович  |   M   |     ст. Серафимович, ул. Советов, д. 92, 659214      |   70114    | 1966-03-12 |  44  |  None  |
|   Феврония  |  |||  |  13 |  Кабанова  |   Феврония  |  Аскольдовна  |  F  |        ст. Ярославль, ул. Дарвина, д. 47, 366771        |  42498   | 1995-01-26 | 113 | 3057 |  3057 |  Моисеев  |  Панкрат   |  Всеволодович |   M   |      п. Яшкуль, ул. Дзержинского, д. 56, 196875      |   81791    | 1956-05-21 | 113  |  None  |
|    Иосиф    |  |||  |  15 |  Суханов   |    Иосиф    |   Валерьевич  |  M  |       п. Домбай, ул. Геологическая, д. 41, 417323       |  70146   | 1980-08-17 |  96 | 4867 |  4867 |   Титова  |  Акулина   |   Руслановна  |   F   |  клх Воскресенск, ул. Комсомольская, д. 90, 036878   |   62388    | 1975-01-25 |  96  |  None  |
|     Осип    |  |||  |  26 |  Степанов  |     Осип    |  Григорьевич  |  M  |     д. Уссурийск, ул. Олега Кошевого, д. 45, 493423     |  57745   | 1971-07-11 |  75 | 3673 |  3673 |  Потапова | Евпраксия  |   Георгиевна  |   F   |   ст. Усть-Джегута, ул. 60 лет СССР, д. 98, 930422   |   133954   | 1962-03-19 |  75  |  None  |
| Максимильян |  |||  |  29 |   Волков   | Максимильян |   Викторович  |  M  |        п. Змеиногорск, ул. Речная, д. 33, 448152        |  72948   | 1989-02-17 | 107 | 1085 |  1085 |   Козлов  |   Герман   | Александрович |   M   |     п. Ногинск (Моск.), ул. Малая, д. 71, 501383     |   73450    | 1978-12-04 | 107  |  None  |
|    Нонна    |  |||  |  46 | Дмитриева  |    Нонна    |    Ждановна   |  F  |         д. Баргузин, ул. Зеленая, д. 00, 721382         |  61400   | 1974-01-18 |  45 | 4812 |  4812 |  Борисова | Александра |   Антоновна   |   F   | с. Пушкинские Горы, ул. Геологическая, д. 48, 775699 |   76190    | 1968-06-19 |  45  |  None  |
|   Виктория  |  |||  |  50 |  Тетерина  |   Виктория  |   Михайловна  |  F  |     д. Каменск-Уральский, ул. Казачья, д. 80, 770797    |  79922   | 1990-02-15 |  57 | 2173 |  2173 |   Блинов  |  Валерьян  |  Герасимович  |   M   |      п. Устюжна, ул. Спортивная, д. 28, 238917       |   100135   | 1963-11-03 |  57  |  273   |
|    Прокл    |  |||  |  75 | Калашников |    Прокл    |   Зиновьевич  |  M  |           с. Валдай, ул. Глинки, д. 75, 701156          |  64829   | 1986-09-04 |  10 | 3066 |  3066 |  Семенова |  Зинаида   |   Даниловна   |   F   |      д. Тырныауз, ул. Жуковского, д. 92, 741913      |   108386   | 1957-08-04 |  10  |  None  |
|    Иванна   |  |||  |  76 |  Колобова  |    Иванна   |   Максимовна  |  F  |         ст. Рубцовск, ул. Герцена, д. 73, 066220        |  44952   | 1998-08-12 |  32 | 3803 |  3803 |   Носков  | Сигизмунд  |   Витальевич  |   M   |        к. Сальск, ул. Беляева, д. 83, 951449         |   89157    | 1980-05-12 |  32  |  None  |
|    Федот    |  |||  |  83 |   Крюков   |    Федот    |   Гордеевич   |  M  |          клх Юровск, ул. Красная, д. 53, 968602         |  56712   | 1980-01-02 |  20 | 778  |  778  |  Цветков  |  Велимир   |  Евстигнеевич |   M   |      клх Тында, ул. Черемуховая, д. 51, 114344       |   77740    | 1973-10-01 |  20  |  5976  |
|   Людмила   |  |||  |  85 |  Петухова  |   Людмила   | Александровна |  F  |      д. Камень-на-Оби, ул. Крупской, д. 83, 813078      |  41053   | 1993-10-26 |  30 | 2640 |  2640 |  Соболева |   Марфа    | Александровна |   F   |     клх Тихорецк, ул. Космонавтов, д. 46, 116422     |   60330    | 1970-10-26 |  30  |  None  |
|    Иванна   |  |||  |  86 |  Евсеева   |    Иванна   |  Болеславовна |  F  | п. Зеленогорск (Ленин.), ул. Запорожская, д. 63, 889602 |  55878   | 1984-01-17 |  24 | 2573 |  2573 |  Костина  |   Фаина    |    Юрьевна    |   F   |       с. Сызрань, ул. Подлесная, д. 16, 117193       |   78989    | 1962-06-14 |  24  |  None  |
+-------------+-------+-----+------------+-------------+---------------+-----+---------------------------------------------------------+----------+------------+-----+------+-------+-----------+------------+---------------+-------+------------------------------------------------------+------------+------------+------+--------+
Truncated to displaylimit of 15.

# 1.12 Названия проектов, выполняемых в месте, в котором размещается отдел, отвечающий за проект.

In [17]:
%%sql
SELECT ПР.Назв, "|||", *
FROM ПР
    JOIN ОТ ON ОТ.No = ПР.Noo --  для проекта, отвечающий за него отдел
    JOIN О_М ON ОТ.No = О_М.No -- место отдела
WHERE
    О_М.Место = ПР.Место -- место проекта совпадает с местом отдела

Running query in 'sqlite:////tmp/db2021.sqlite'

+-------------------+-------+-----+-------------------+---------------+-----+-----+----------------------------------------------------------+------+------------+------+---------------+
|        Назв       | "|||" |  Np |       Назв_1      |     Место     | Noo |  No |                          Назв_2                          | КодР |    НачР    | No_1 |    Место_1    |
+-------------------+-------+-----+-------------------+---------------+-----+-----+----------------------------------------------------------+------+------------+------+---------------+
| KOUOU-47419-SCKYS |  |||  |  2  | KOUOU-47419-SCKYS | с. Курганинск | 123 | 123 |        Отдел информатизации внутренних технологий        | 6323 | 2015-01-15 | 123  | с. Курганинск |
| ZEGIO-91152-PBALK |  |||  |  7  | ZEGIO-91152-PBALK |   клх Шарья   |  53 |  53 |           Отдел содержания внешних технологий            | 5865 | 2014-03-30 |  53  |   клх Шарья   |
| KHDGE-56273-MRNQQ |  |||  |  22 | KHDGE-56273-MRNQQ |   клх Миасс   |  42 |  42 |       Отдел обеспечения промежуточных исследований       | 4171 | 2015-11-10 |  42  |   клх Миасс   |
| WYCTG-24702-CUFFK |  |||  |  29 | WYCTG-24702-CUFFK |    к. Тура    |  3  |  3  |          Отдел управления внутренних технологий          | 5983 | 2016-07-03 |  3   |    к. Тура    |
| NIBQS-51316-AZXQP |  |||  |  53 | NIBQS-51316-AZXQP |   г. Домбай   | 107 | 107 | Отдел юридического сопровождения внутренних исследований | 1085 | 2017-05-28 | 107  |   г. Домбай   |
| JBPVP-17060-RIYIY |  |||  |  69 | JBPVP-17060-RIYIY |    п. Хасан   |  63 |  63 |           Отдел контроля внутренних технологий           | 974  | 2016-11-06 |  63  |    п. Хасан   |
| CZZPY-33031-LEHST |  |||  |  70 | CZZPY-33031-LEHST | с. Домодедово | 129 | 129 |          Отдел информатизации внешних проектов           | 567  | 2016-09-04 | 129  | с. Домодедово |
| WFXWJ-72998-WXJXH |  |||  |  79 | WFXWJ-72998-WXJXH |    к. Тура    |  74 |  74 |          Отдел контроля промежуточных проектов           | 952  | 2013-08-25 |  74  |    к. Тура    |
| DHOUL-13713-IUJXG |  |||  |  88 | DHOUL-13713-IUJXG |   клх Миасс   |  96 |  96 |          Отдел финансирования внешних операций           | 2109 | 2014-04-04 |  96  |   клх Миасс   |
| TJIDI-73787-UMEYN |  |||  |  96 | TJIDI-73787-UMEYN |   клх Миасс   |  62 |  62 |          Отдел контроля внутренних исследований          | 6180 | 2013-03-12 |  62  |   клх Миасс   |
| DSQJV-18565-PAMQJ |  |||  |  99 | DSQJV-18565-PAMQJ |   клх Губаха  | 113 | 113 |   Отдел юридического сопровождения внешних технологий    | 553  | 2018-12-08 | 113  |   клх Губаха  |
| NWZHT-88218-SJBTR |  |||  | 124 | NWZHT-88218-SJBTR | с. Курганинск |  63 |  63 |           Отдел контроля внутренних технологий           | 974  | 2016-11-06 |  63  | с. Курганинск |
| NOWKS-64304-KGUJU |  |||  | 145 | NOWKS-64304-KGUJU |  п. Усть-Ишим |  58 |  58 |        Отдел содержания промежуточных технологий         | 4511 | 2015-12-16 |  58  |  п. Усть-Ишим |
| AOCMK-52792-MJKPM |  |||  | 149 | AOCMK-52792-MJKPM |   клх Шарья   |  61 |  61 |            Отдел контроля внутренних операций            | 2139 | 2017-08-18 |  61  |   клх Шарья   |
| OHMIU-29749-PLQWA |  |||  | 154 | OHMIU-29749-PLQWA | с. Домодедово |  28 |  28 |        Отдел мониторинга промежуточных технологий        | 2631 | 2016-12-04 |  28  | с. Домодедово |
+-------------------+-------+-----+-------------------+---------------+-----+-----+----------------------------------------------------------+------+------------+------+---------------+
Truncated to displaylimit of 15.

# 1.13 Номера проектов, над которыми работает Иванов, но отдел, в котором он работает, не отвечает за проект

In [18]:
%%sql
SELECT ПР.Np, "|||", *
FROM ПР
    JOIN Р_Н ON Р_Н.Np = ПР.Np -- для проекта, кто работает над ним
    JOIN СЛ ON СЛ.Код = Р_Н.Код -- его имя и отдел
WHERE
    СЛ.No != ПР.Noo -- работает в отделе, который не отвечает за проект
    AND СЛ.Фамилия = "Иванов" -- !! в базе данных нет имени Иванов !!

Running query in 'sqlite:////tmp/db2021.sqlite'

+----+-------+------+------+-------+-----+-----+------+-------+-------+---------+-----+----------+-----+-------+----------+-------+----+------+
| Np | "|||" | Np_1 | Назв | Место | Noo | Код | Np_2 | Время | Код_1 | Фамилия | Имя | Отчество | Пол | Адрес | Зарплата | Дрожд | No | КодК |
+----+-------+------+------+-------+-----+-----+------+-------+-------+---------+-----+----------+-----+-------+----------+-------+----+------+
+----+-------+------+------+-------+-----+-----+------+-------+-------+---------+-----+----------+-----+-------+----------+-------+----+------+

---
# 2.3 Выдать номера проектов, над которыми работают {только / все / только и все} сотрудники отдела, отвечающего за проект.

In [19]:
%%sql --save only_employees_of_dep
-- Выдать номера проектов, над которыми работают {только} сотрудники отдела, отвечающего за проект.
SELECT ПР.Np FROM ПР -- ищем такие проекты,
WHERE NOT EXISTS ( -- что не бывает...
    SELECT * FROM Р_Н JOIN СЛ ON СЛ.Код = Р_Н.Код -- таких сотрудников...
    WHERE
        Р_Н.Np = ПР.Np -- которые работают над этим проектом,
        AND СЛ.No != ПР.Noo -- но они работают не в отделе этого проекта
)

Running query in 'sqlite:////tmp/db2021.sqlite'

+----+
| Np |
+----+
| 1  |
| 2  |
| 3  |
| 4  |
| 5  |
| 6  |
| 7  |
| 8  |
| 9  |
| 10 |
| 11 |
| 12 |
| 13 |
| 14 |
| 15 |
+----+
Truncated to displaylimit of 15.

In [20]:
%%sql --save all_employees_of_dep 
-- Выдать номера проектов, над которыми работают {все} сотрудники отдела, отвечающего за проект.
SELECT Np FROM ПР -- для каждого проекта,
NATURAL JOIN (
    SELECT Р_Н.Np, СЛ.No, count(1) project_population  -- посчитаем количество людей,
    FROM Р_Н -- которые работают над этим проектом,
    NATURAL JOIN СЛ
    GROUP BY Np, No -- и распределим их по отделам, из которых они.
)
NATURAL JOIN (SELECT СЛ.No AS Noo, count(1) total_population FROM СЛ GROUP BY No) -- затем посчитаем количество людей в отделе, который ответственный за проект.
WHERE No = Noo -- рассмотрим только тех людей, которые работают в ответственном отделе: если тех, кто работает над проектом, столько же, сколько всего людей в отделе, значит над проектом работает весь отдел
AND project_population = total_population

Running query in 'sqlite:////tmp/db2021.sqlite'

+----+
| Np |
+----+
+----+

In [21]:
%%sql --with only_employees_of_dep --with all_employees_of_dep
-- Выдать номера проектов, над которыми работают {только и все} сотрудники отдела, отвечающего за проект.
SELECT Np FROM only_employees_of_dep -- проекты, над которыми работают только свои
INTERSECT                           -- и среди них
SELECT Np FROM all_employees_of_dep -- проекты, над которыми работает весь отдел

Running query in 'sqlite:////tmp/db2021.sqlite'

+----+
| Np |
+----+
+----+

---
# 3.5 Названия отделов, численность которых больше 10 человек, а средняя зарплата меньше 500 рублей.

In [22]:
%%sql --save big_population --no-execute
SELECT No, COUNT(1) AS population -- считаем население каждого отдела
FROM СЛ
GROUP BY No -- и фильтруем только те, где оно высокое !!ДАННЫЕ ИЗМЕНЕНЫ!!
HAVING population>50

Running query in 'sqlite:////tmp/db2021.sqlite'

Skipping execution...

In [23]:
%%sql --save low_salary --no-execute
SELECT No, AVG(Зарплата) AS depsalary -- для каждого отдела ищем среднюю зарплату
FROM СЛ
GROUP BY No -- и фильтруем только те, где она низкая !!ДАННЫЕ ИЗМЕНЕНЫ!!
HAVING depsalary < 70000

Running query in 'sqlite:////tmp/db2021.sqlite'

Skipping execution...

In [24]:
%%sql --with big_population --with low_salary
SELECT No FROM (
    SELECT No FROM big_population
    INTERSECT
    SELECT No FROM low_salary
    )

Running query in 'sqlite:////tmp/db2021.sqlite'

+-----+
|  No |
+-----+
|  6  |
|  8  |
|  24 |
|  31 |
|  49 |
|  51 |
|  77 |
|  87 |
| 107 |
| 116 |
| 122 |
| 128 |
| 135 |
+-----+

# 3.6. Номера проектов, для которых из всех работающих над ними более половины сотрудники отвечающего отдела.

In [25]:
%%sql --save project_population 
SELECT Np, count(1) AS total_population -- для каждого проекта ищем его общее население
FROM Р_Н
GROUP BY Р_Н.Np

Running query in 'sqlite:////tmp/db2021.sqlite'

+----+------------------+
| Np | total_population |
+----+------------------+
| 1  |        12        |
| 2  |        11        |
| 3  |        15        |
| 4  |        10        |
| 5  |        11        |
| 6  |        14        |
| 7  |        9         |
| 8  |        17        |
| 9  |        16        |
| 10 |        12        |
| 11 |        21        |
| 12 |        9         |
| 13 |        11        |
| 14 |        12        |
| 15 |        7         |
+----+------------------+
Truncated to displaylimit of 15.

In [26]:
%%sql --save project_selfdep_population 
SELECT ПР.Np, count(1) AS selfdep_population -- для каждого проекта ищем его население,
    FROM Р_Н
    JOIN СЛ ON СЛ.Код = Р_Н.Код -- но только для тех служащих,
    JOIN ПР ON ПР.Np = Р_Н.Np -- что, если посмотреть на проект над которым они работают,
WHERE СЛ.No = ПР.Noo -- то за этот проект отвечает тот отдел, где работает этот служащий
GROUP BY ПР.Np

Running query in 'sqlite:////tmp/db2021.sqlite'

+----+--------------------+
| Np | selfdep_population |
+----+--------------------+
| 1  |         12         |
| 2  |         11         |
| 3  |         15         |
| 4  |         10         |
| 5  |         11         |
| 6  |         14         |
| 7  |         9          |
| 8  |         17         |
| 9  |         16         |
| 10 |         12         |
| 11 |         21         |
| 12 |         9          |
| 13 |         11         |
| 14 |         12         |
| 15 |         7          |
+----+--------------------+
Truncated to displaylimit of 15.

In [27]:
%%sql --with project_population --with project_selfdep_population
SELECT Np, (selfdep_population/total_population) proportion -- для каждого проекта посчитать отношение
FROM project_population -- между полным населением
NATURAL JOIN project_selfdep_population -- и населением из собственного отдела
WHERE proportion > 0.5 -- и выдавать только те, где эта пропорция больше 50%

Running query in 'sqlite:////tmp/db2021.sqlite'

+----+------------+
| Np | proportion |
+----+------------+
| 1  |     1      |
| 2  |     1      |
| 3  |     1      |
| 4  |     1      |
| 5  |     1      |
| 6  |     1      |
| 7  |     1      |
| 8  |     1      |
| 9  |     1      |
| 10 |     1      |
| 11 |     1      |
| 12 |     1      |
| 13 |     1      |
| 14 |     1      |
| 15 |     1      |
+----+------------+
Truncated to displaylimit of 15.

# 3.7 Названия отделов, в которых более трех служащих имеют двух иждивенцев, родившихся в 2012 году.

In [28]:
%%sql --save employees_with_matching_deps --no-execute
SELECT СЛ.Код, СЛ.No, count(ИЖД.Имя) AS dep_count -- считаем число иждивенцев
FROM СЛ                                           -- для каждого служащего --
LEFT OUTER JOIN ИЖД ON ИЖД.Код = СЛ.Код           -- даже для тех, у кого иждивенцев нет
WHERE ИЖД.Дрожд LIKE "20%"                        -- и проверяем, что их дата рождения правильная !!ДАННЫЕ ИЗМЕНЕНЫ!!
GROUP BY СЛ.Код  -- выводим только тех, у кого ровно два иждивенца с правильной датой рождения
HAVING dep_count=2

Running query in 'sqlite:////tmp/db2021.sqlite'

Skipping execution...

In [29]:
%%sql --with employees_with_matching_deps --save deps_with_matching_employees
SELECT No, count(1) AS emp_count FROM employees_with_matching_deps -- считаем, сколько сотрудников с правильными иждивенцами
GROUP BY No -- есть в каждом отделе, а затем берем только те отделы, где таких сотрудников больше 3.
HAVING emp_count>3

Running query in 'sqlite:////tmp/db2021.sqlite'

+-----+-----------+
|  No | emp_count |
+-----+-----------+
| 106 |     5     |
+-----+-----------+

In [30]:
%%sql --with deps_with_matching_employees
SELECT ОТ.Назв, "|||", *
FROM ОТ -- выписываем названия отделов,
NATURAL JOIN deps_with_matching_employees -- которые мы перечислили

Running query in 'sqlite:////tmp/db2021.sqlite'

+------------------------------------------------------+-------+-----+------------------------------------------------------+------+------------+-----------+
|                         Назв                         | "|||" |  No |                        Назв_1                        | КодР |    НачР    | emp_count |
+------------------------------------------------------+-------+-----+------------------------------------------------------+------+------------+-----------+
| Отдел юридического сопровождения внутренних операций |  |||  | 106 | Отдел юридического сопровождения внутренних операций | 1188 | 2018-12-17 |     5     |
+------------------------------------------------------+-------+-----+------------------------------------------------------+------+------------+-----------+

# 3.8 Номера проектов, в работе над которыми наибольшее время затрачивает сотрудник отвечающего отдела.

In [31]:
%%sql
SELECT ПР.Np, "|||", СЛ.Код,  --  ищем проекты, где сотрудник работал максимальное время
max(Время)
FROM Р_Н
    JOIN ПР ON ПР.Np = Р_Н.Np -- подключая данные о проекте
    JOIN СЛ ON Р_Н.Код = СЛ.Код -- и о сотруднике
GROUP BY ПР.Np -- ищем максимум для каждого проекта
HAVING СЛ.No = ПР.Noo -- и оставляем только те максимумы, где самое большое время от своего отдела

Running query in 'sqlite:////tmp/db2021.sqlite'

+----+-------+------+------------+
| Np | "|||" | Код  | max(Время) |
+----+-------+------+------------+
| 1  |  |||  | 1278 |     12     |
| 2  |  |||  | 1551 |     13     |
| 3  |  |||  | 1011 |     14     |
| 4  |  |||  | 851  |     11     |
| 5  |  |||  | 496  |     14     |
| 6  |  |||  | 6233 |     14     |
| 7  |  |||  | 826  |     13     |
| 8  |  |||  | 3188 |     13     |
| 9  |  |||  | 848  |     16     |
| 10 |  |||  | 3441 |     12     |
| 11 |  |||  | 5879 |     14     |
| 12 |  |||  | 4400 |     11     |
| 13 |  |||  | 598  |     11     |
| 14 |  |||  | 1255 |     11     |
| 15 |  |||  | 3052 |     8      |
+----+-------+------+------------+
Truncated to displaylimit of 15.

# 3.9 Номера проектов, в работе над которыми наибольшее время затрачива[ю]т сотрудник[и] отвечающего отдела.

In [32]:
%%sql --save project_deps_time_contribution --no-execute
SELECT ПР.Np, ОТ.No, coalesce(sum(t1.Время), 0) AS dep_time -- собираем таблицу, где написано,
FROM ПР -- для каждого проекта
    CROSS JOIN ОТ -- и каждого отдела
    LEFT OUTER JOIN ( -- (даже если никто из отдела не работал над этим проектом)
        SELECT Р_Н.*, СЛ.No FROM Р_Н -- выбираем сотрудников,
        JOIN СЛ ON СЛ.Код = Р_Н.Код 
    ) t1 ON ПР.Np = t1.Np AND t1.No = ОТ.No -- которые работали над этим проектом и из этого отдела
GROUP BY ПР.Np,  -- суммируем время для каждого проекта и отдела, между всеми сотрудниками
ОТ.No

Running query in 'sqlite:////tmp/db2021.sqlite'

Skipping execution...

In [33]:
%%sql --with project_deps_time_contribution
SELECT Np, "|||", * FROM (
    SELECT pdtc.Np, No, max(pdtc.dep_time) AS max_time -- ищем тот отдел, который провел больше всего времени 
    FROM project_deps_time_contribution AS pdtc
    GROUP BY Np -- над одним проектом
)
NATURAL JOIN ПР -- затем проверяем, что за проект
WHERE ПР.Noo = No -- отвечает тот отдел, что провел макс. время

Running query in 'sqlite:////tmp/db2021.sqlite'

+----+-------+------+-----+----------+-------------------+--------------------+-----+
| Np | "|||" | Np_1 |  No | max_time |        Назв       |       Место        | Noo |
+----+-------+------+-----+----------+-------------------+--------------------+-----+
| 1  |  |||  |  1   |  15 |    90    | WOEJU-28806-BCTUR |     ст. Кяхта      |  15 |
| 2  |  |||  |  2   | 123 |    94    | KOUOU-47419-SCKYS |   с. Курганинск    | 123 |
| 3  |  |||  |  3   | 116 |   130    | UUNKB-66648-TSDYJ |      ст. Омск      | 116 |
| 4  |  |||  |  4   |  39 |    88    | PKRNG-43766-SZCUT |      ст. Омск      |  39 |
| 5  |  |||  |  5   |  13 |    88    | HVINS-74362-VJNSL | с. Троицко-Печорск |  13 |
| 6  |  |||  |  6   |  38 |   123    | OLJWL-51887-OCDQI |     г. Домбай      |  38 |
| 7  |  |||  |  7   |  53 |    83    | ZEGIO-91152-PBALK |     клх Шарья      |  53 |
| 8  |  |||  |  8   | 100 |   133    | SFBXO-67717-JBDYI |    д. Куртамыш     | 100 |
| 9  |  |||  |  9   |  92 |   154    | YTJNI-58784-EAGUS | с. Троицко-Печорск |  92 |
| 10 |  |||  |  10  |  11 |    87    | YCBHJ-30508-VDQQH |     клх Талдом     |  11 |
| 11 |  |||  |  11  |  16 |   166    | QHACA-16216-KENQK |     клх Крымск     |  16 |
| 12 |  |||  |  12  | 105 |    72    | SAUUP-18393-BBHYE |     клх Выборг     | 105 |
| 13 |  |||  |  13  |  36 |    93    | INATV-96258-RDAGV |  д. Южно-Курильск  |  36 |
| 14 |  |||  |  14  | 120 |    96    | GABED-87652-BWQAS |      к. Елец       | 120 |
| 15 |  |||  |  15  |  36 |    45    | XBULD-65698-OEYQL |      п. Хасан      |  36 |
+----+-------+------+-----+----------+-------------------+--------------------+-----+
Truncated to displaylimit of 15.

---
# 4.2 Номера проектов, имя руководителя отвечающего отдела и количество служащих, работающих над проектом при условии, что руководитель работает над не менее чем 2-мя другими проектами.

In [34]:
%%sql --save project_population --no-execute
SELECT Р_Н.Np, count(1) AS population -- ищем население проекта
FROM Р_Н -- для каждого проекта
GROUP BY Np

Running query in 'sqlite:////tmp/db2021.sqlite'

Skipping execution...

In [35]:
%%sql --save big_boss --no-execute
SELECT Р_Н.Код, count(1) boss_proj_count -- ищем количество проектов,
FROM Р_Н -- над которыми работает один сотрудник
GROUP BY Р_Н.Код -- и оставляем только таких сотрудников, которые работают над больше чем 3.
HAVING boss_proj_count > 3

Running query in 'sqlite:////tmp/db2021.sqlite'

Skipping execution...

In [36]:
%%sql --with project_population --with big_boss
SELECT DISTINCT Np, СЛ.Имя,  population, "|||", *
FROM ПР --для каждого проекта,
NATURAL JOIN project_population -- подключаем его население,
NATURAL JOIN big_boss -- оставляем только те, где начальник работает над 3 проектами
JOIN ОТ ON ПР.Noo = ОТ.No -- затем ищем отдел проекта
JOIN СЛ ON СЛ.Код = ОТ.КодР -- и начальника этого проекта;
WHERE EXISTS ( -- также должен
    SELECT * FROM Р_Н 
    WHERE Р_Н.Код = СЛ.Код -- начальник работать
        AND Р_Н.Np = ПР.Np -- над рассматриваемым проектом
)

Running query in 'sqlite:////tmp/db2021.sqlite'

+----+--------+------------+-------+------+-------------------+---------------+-----+--------------+-----+-----------------+-----+--------------------------------------------+------+------------+-------+---------+--------+-------------+-----+---------------------------------------------+----------+------------+------+------+
| Np |  Имя   | population | "|||" | Np_1 |        Назв       |     Место     | Noo | population_1 | Код | boss_proj_count |  No |                   Назв_1                   | КодР |    НачР    | Код_1 | Фамилия | Имя_1  |   Отчество  | Пол |                    Адрес                    | Зарплата |   Дрожд    | No_1 | КодК |
+----+--------+------------+-------+------+-------------------+---------------+-----+--------------+-----+-----------------+-----+--------------------------------------------+------+------------+-------+---------+--------+-------------+-----+---------------------------------------------+----------+------------+------+------+
| 2  | Прохор |     11     |  |||  |  2   | KOUOU-47419-SCKYS | с. Курганинск | 123 |      11      |  47 |        4        | 123 | Отдел информатизации внутренних технологий | 6323 | 2015-01-15 |  6323 |  Евсеев | Прохор | Григорьевич |  M  | с. Карабудахкент, ул. Омская, д. 90, 900852 |  88479   | 1968-10-13 | 123  | None |
| 2  | Прохор |     11     |  |||  |  2   | KOUOU-47419-SCKYS | с. Курганинск | 123 |      11      |  64 |        5        | 123 | Отдел информатизации внутренних технологий | 6323 | 2015-01-15 |  6323 |  Евсеев | Прохор | Григорьевич |  M  | с. Карабудахкент, ул. Омская, д. 90, 900852 |  88479   | 1968-10-13 | 123  | None |
| 2  | Прохор |     11     |  |||  |  2   | KOUOU-47419-SCKYS | с. Курганинск | 123 |      11      |  94 |        5        | 123 | Отдел информатизации внутренних технологий | 6323 | 2015-01-15 |  6323 |  Евсеев | Прохор | Григорьевич |  M  | с. Карабудахкент, ул. Омская, д. 90, 900852 |  88479   | 1968-10-13 | 123  | None |
| 2  | Прохор |     11     |  |||  |  2   | KOUOU-47419-SCKYS | с. Курганинск | 123 |      11      | 142 |        4        | 123 | Отдел информатизации внутренних технологий | 6323 | 2015-01-15 |  6323 |  Евсеев | Прохор | Григорьевич |  M  | с. Карабудахкент, ул. Омская, д. 90, 900852 |  88479   | 1968-10-13 | 123  | None |
| 2  | Прохор |     11     |  |||  |  2   | KOUOU-47419-SCKYS | с. Курганинск | 123 |      11      | 213 |        5        | 123 | Отдел информатизации внутренних технологий | 6323 | 2015-01-15 |  6323 |  Евсеев | Прохор | Григорьевич |  M  | с. Карабудахкент, ул. Омская, д. 90, 900852 |  88479   | 1968-10-13 | 123  | None |
| 2  | Прохор |     11     |  |||  |  2   | KOUOU-47419-SCKYS | с. Курганинск | 123 |      11      | 219 |        4        | 123 | Отдел информатизации внутренних технологий | 6323 | 2015-01-15 |  6323 |  Евсеев | Прохор | Григорьевич |  M  | с. Карабудахкент, ул. Омская, д. 90, 900852 |  88479   | 1968-10-13 | 123  | None |
| 2  | Прохор |     11     |  |||  |  2   | KOUOU-47419-SCKYS | с. Курганинск | 123 |      11      | 229 |        5        | 123 | Отдел информатизации внутренних технологий | 6323 | 2015-01-15 |  6323 |  Евсеев | Прохор | Григорьевич |  M  | с. Карабудахкент, ул. Омская, д. 90, 900852 |  88479   | 1968-10-13 | 123  | None |
| 2  | Прохор |     11     |  |||  |  2   | KOUOU-47419-SCKYS | с. Курганинск | 123 |      11      | 241 |        5        | 123 | Отдел информатизации внутренних технологий | 6323 | 2015-01-15 |  6323 |  Евсеев | Прохор | Григорьевич |  M  | с. Карабудахкент, ул. Омская, д. 90, 900852 |  88479   | 1968-10-13 | 123  | None |
| 2  | Прохор |     11     |  |||  |  2   | KOUOU-47419-SCKYS | с. Курганинск | 123 |      11      | 254 |        4        | 123 | Отдел информатизации внутренних технологий | 6323 | 2015-01-15 |  6323 |  Евсеев | Прохор | Григорьевич |  M  | с. Карабудахкент, ул. Омская, д. 90, 900852 |  88479   | 1968-10-13 | 123  | None |
| 2  | Прохор |     11     |  |||  |  2   | KOUOU-47419-SCKYS | с. Курганинск | 123 |      11      | 258 |        4        | 123 | Отдел информатизации внутренних технологий | 6323 | 2015-01-15 |  6323 |  Евсеев | Прохор | Григорьевич |  M  | с. Карабудахкент, ул. Омская, д. 90, 900852 |  88479   | 1968-10-13 | 123  | None |
| 2  | Прохор |     11     |  |||  |  2   | KOUOU-47419-SCKYS | с. Курганинск | 123 |      11      | 292 |        4        | 123 | Отдел информатизации внутренних технологий | 6323 | 2015-01-15 |  6323 |  Евсеев | Прохор | Григорьевич |  M  | с. Карабудахкент, ул. Омская, д. 90, 900852 |  88479   | 1968-10-13 | 123  | None |
| 2  | Прохор |     11     |  |||  |  2   | KOUOU-47419-SCKYS | с. Курганинск | 123 |      11      | 344 |        5        | 123 | Отдел информатизации внутренних технологий | 6323 | 2015-01-15 |  6323 |  Евсеев | Прохор | Григорьевич |  M  | с. Карабудахкент, ул. Омская, д. 90, 900852 |  88479   | 1968-10-13 | 123  | None |
| 2  | Прохор |     11     |  |||  |  2   | KOUOU-47419-SCKYS | с. Курганинск | 123 |      11      | 348 |        4        | 123 | Отдел информатизации внутренних технологий | 6323 | 2015-01-15 |  6323 |  Евсеев | Прохор | Григорьевич |  M  | с. Карабудахкент, ул. Омская, д. 90, 900852 |  88479   | 1968-10-13 | 123  | None |
| 2  | Прохор |     11     |  |||  |  2   | KOUOU-47419-SCKYS | с. Курганинск | 123 |      11      | 364 |        4        | 123 | Отдел информатизации внутренних технологий | 6323 | 2015-01-15 |  6323 |  Евсеев | Прохор | Григорьевич |  M  | с. Карабудахкент, ул. Омская, д. 90, 900852 |  88479   | 1968-10-13 | 123  | None |
| 2  | Прохор |     11     |  |||  |  2   | KOUOU-47419-SCKYS | с. Курганинск | 123 |      11      | 366 |        4        | 123 | Отдел информатизации внутренних технологий | 6323 | 2015-01-15 |  6323 |  Евсеев | Прохор | Григорьевич |  M  | с. Карабудахкент, ул. Омская, д. 90, 900852 |  88479   | 1968-10-13 | 123  | None |
+----+--------+------------+-------+------+-------------------+---------------+-----+--------------+-----+-----------------+-----+--------------------------------------------+------+------------+-------+---------+--------+-------------+-----+---------------------------------------------+----------+------------+------+------+
Truncated to displaylimit of 15.